version: '3'
services:
  database:
    image: postgres:13.0
    restart: always
    environment:
      POSTGRES_DB: mydbname
      POSTGRES_USER: mydbuser
      POSTGRES_PASSWORD: mydbpwd
    ports:
      - "5433:5432"
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://mydbuser:mydbpwd@database:5432/mydbname?sslmode=disable", "-verbose", "up"]
    restart: on-failure
    depends_on:
      - database
    links:
      - database
